'use strict';
const $=id=>document.getElementById(id);
let map,routeLines=[],pins=[],routes=[],routeRevision=0,mapReady=false;
const places={start:null,end:null};
const searchRevisions={start:0,end:0};
const inputTimers={};
const searchSessions={start:crypto.randomUUID(),end:crypto.randomUUID()};
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
async function api(path,payload,signal){const response=await fetch(path,{method:payload?'POST':'GET',headers:payload?{'Content-Type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined,signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not complete the request.');return data;}
function updateButton(){ $('find').disabled=!(mapReady&&places.start&&places.end); }
function resetRoute(){routeRevision++;routes=[];routeLines.forEach(line=>line.setMap(null));routeLines=[];$('route-options').replaceChildren();$('route-details').hidden=true;updateButton();}
function updatePins(){pins.forEach(pin=>pin.setMap(null));pins=[];if(!map)return;for(const [key,label] of [['start','A'],['end','B']])if(places[key])pins.push(new google.maps.Marker({map,position:places[key].location,label:{text:label,color:'#fff',fontWeight:'700'},icon:{path:google.maps.SymbolPath.CIRCLE,scale:13,fillColor:key==='start'?'#204f3b':'#769d43',fillOpacity:1,strokeColor:'#fff',strokeWeight:3}}));}
function closeResults(key){$(key+'-results').hidden=true;$(key).setAttribute('aria-expanded','false');}
async function choose(key,prediction){
 const revision=++searchRevisions[key];clearTimeout(inputTimers[key]);closeResults(key);
 status('Checking the selected address…');
 try{
  const place=await api('/api/google/place?'+new URLSearchParams({id:prediction.id,session:searchSessions[key]}));
  if(revision!==searchRevisions[key])return;
  const location={lat:place.location?.latitude,lng:place.location?.longitude};
  if(!Number.isFinite(location.lat)||!Number.isFinite(location.lng))throw new Error('Google did not return a map location for this place. Choose another suggestion.');
  searchSessions[key]=crypto.randomUUID();places[key]={...place,location};
  $(key).value=place.formattedAddress||prediction.label;resetRoute();updatePins();
  if(map){map.panTo(location);map.setZoom(14);}
  status(places.start&&places.end?'Ready when you are. Find your cycling route.':'Location selected. Add the other end of your ride.');
 }catch(error){if(revision===searchRevisions[key])status(error.message,true);}
}
for(const key of ['start','end']){
 $(key).addEventListener('input',()=>{places[key]=null;resetRoute();updatePins();clearTimeout(inputTimers[key]);const revision=++searchRevisions[key];const query=$(key).value.trim();closeResults(key);if(!query)return;inputTimers[key]=setTimeout(async()=>{const list=$(key+'-results');list.replaceChildren();const note=document.createElement('span');note.className='search-note';note.textContent='Searching Google Maps…';list.append(note);list.hidden=false;$(key).setAttribute('aria-expanded','true');try{const result=await api('/api/google/autocomplete?'+new URLSearchParams({q:query,session:searchSessions[key]}));if(revision!==searchRevisions[key])return;list.replaceChildren();for(const place of result.suggestions||[]){const button=document.createElement('button');button.type='button';button.setAttribute('role','option');const title=document.createElement('strong'),address=document.createElement('small');title.textContent=place.label;address.textContent='Select this location';button.append(title,address);button.onclick=()=>choose(key,place);list.append(button);}const credit=document.createElement('span');credit.className='search-note';credit.textContent=result.suggestions?.length?'Google Maps':'No places found. Try a complete address and city.';list.append(credit);}catch(error){if(revision!==searchRevisions[key])return;list.replaceChildren();const note=document.createElement('span');note.className='search-note';note.textContent=error.message;list.append(note);}},250);});
 $(key).addEventListener('keydown',event=>{const list=$(key+'-results');if(event.key==='Escape'){searchRevisions[key]++;closeResults(key);}if(event.key==='ArrowDown'&&!list.hidden){event.preventDefault();list.querySelector('button')?.focus();}if(event.key==='Enter'){event.preventDefault();if(!list.hidden)list.querySelector('button')?.click();else if(places.start&&places.end)$('trip-form').requestSubmit();}});
 $(key+'-results').addEventListener('keydown',event=>{if(event.key==='Escape'){closeResults(key);$(key).focus();}if(event.key==='ArrowDown'){event.preventDefault();event.target.nextElementSibling?.focus();}if(event.key==='ArrowUp'){event.preventDefault();if(event.target.previousElementSibling)event.target.previousElementSibling.focus();else $(key).focus();}});
}
document.addEventListener('click',event=>{for(const key of ['start','end'])if(!$(key).parentElement.contains(event.target))closeResults(key);});
$('swap').onclick=()=>{for(const key of ['start','end']){searchRevisions[key]++;clearTimeout(inputTimers[key]);closeResults(key);} [places.start,places.end]=[places.end,places.start];[$('start').value,$('end').value]=[$('end').value,$('start').value];resetRoute();updatePins();status('Locations swapped. Find your new route.');};
function decodePolyline(encoded){let index=0,lat=0,lng=0;const path=[];while(index<encoded.length){const values=[];for(let i=0;i<2;i++){let shift=0,result=0,b;do{b=encoded.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5;}while(b>=32);values.push(result&1?~(result>>1):result>>1);}lat+=values[0];lng+=values[1];path.push({lat:lat/1e5,lng:lng/1e5});}return path;}
function minutes(route){return Math.round(parseFloat(route.duration||'0')/60);}
function miles(distance){return (distance/1609.344).toFixed(1)+' mi';}
function fitRoute(path){if(!path?.length)return;const bounds=new google.maps.LatLngBounds();path.forEach(point=>bounds.extend(point));map.fitBounds(bounds,{top:85,right:45,bottom:110,left:45});}
function selectRoute(index){routeLines.forEach(line=>line.setMap(null));routeLines=[];document.querySelectorAll('.route-option').forEach((button,i)=>{button.classList.toggle('selected',i===index);button.setAttribute('aria-pressed',String(i===index));});const route=routes[index],path=decodePolyline(route.polyline.encodedPolyline);for(const [color,weight] of [['#ffffff',10],['#204f3b',6]])routeLines.push(new google.maps.Polyline({map,path,strokeColor:color,strokeOpacity:1,strokeWeight:weight,zIndex:3}));fitRoute(path);$('fit').onclick=()=>fitRoute(path);$('route-details').hidden=false;$('directions').replaceChildren();let count=0;for(const leg of route.legs||[])for(const step of leg.steps||[]){const li=document.createElement('li'),number=document.createElement('span'),copy=document.createElement('div'),distance=document.createElement('small');number.className='step-number';number.textContent=++count;copy.textContent=step.navigationInstruction?.instructions||'Continue along the route';distance.textContent=step.distanceMeters?(step.distanceMeters<160?Math.round(step.distanceMeters*3.28084)+' ft':miles(step.distanceMeters)):'Arrive';copy.append(distance);li.append(number,copy);$('directions').append(li);}$('warnings').textContent=[...(route.warnings||[]),'Google cycling routes may use streets and do not guarantee a sidewalk-only ride.'].join(' ');$('open-google').href='https://www.google.com/maps/dir/?'+new URLSearchParams({api:'1',origin:places.start.formattedAddress,destination:places.end.formattedAddress,origin_place_id:places.start.id,destination_place_id:places.end.id,travelmode:'bicycling'});status('Route found by Google Maps. Select a route to compare your options.');}
$('trip-form').onsubmit=async event=>{event.preventDefault();if(!places.start||!places.end||!mapReady)return;resetRoute();const revision=routeRevision;$('find').disabled=true;status('Finding your cycling route with Google Maps…');try{const result=await api('/api/google/route',{origin:places.start.id,destination:places.end.id});if(revision!==routeRevision)return;routes=(result.routes||[]).filter(route=>route.polyline?.encodedPolyline).sort((a,b)=>a.distanceMeters-b.distanceMeters);if(!routes.length){status('Google did not return a cycling route for these locations. Try another destination.',true);return;}routes.forEach((route,index)=>{const button=document.createElement('button');button.type='button';button.className='route-option';const copy=document.createElement('span'),time=document.createElement('strong'),label=document.createElement('small'),distance=document.createElement('span');time.textContent=minutes(route)+' min';label.textContent=index===0?'Shortest returned cycling route':'Alternative '+index;distance.textContent=miles(route.distanceMeters);copy.append(time,label);button.append(copy,distance);button.onclick=()=>selectRoute(index);$('route-options').append(button);});selectRoute(0);}catch(error){if(revision===routeRevision)status(error.message,true);}finally{if(revision===routeRevision)updateButton();}};
function setMapStyle(style){if(map)map.setMapTypeId(style==='satellite'?'satellite':'roadmap');$('street').classList.toggle('selected',style==='street');$('satellite').classList.toggle('selected',style==='satellite');}
$('street').onclick=()=>setMapStyle('street');$('satellite').onclick=()=>setMapStyle('satellite');
function mapError(text){$('map-error').textContent=text;$('map-error').hidden=false;status(text,true);mapReady=false;updateButton();}
window.gm_authFailure=()=>mapError('Google rejected the map key. Check Google Maps access for this demo key.');
window.initSidepath=()=>{map=new google.maps.Map($('map'),{center:{lat:26.365,lng:-80.115},zoom:13,disableDefaultUI:true,zoomControl:true,zoomControlOptions:{position:google.maps.ControlPosition.RIGHT_CENTER},streetViewControl:true,fullscreenControl:true,gestureHandling:'greedy',styles:[{featureType:'poi',elementType:'labels',stylers:[{visibility:'off'}]},{featureType:'landscape',elementType:'geometry',stylers:[{color:'#f1f3e9'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#b9d9df'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#ffffff'}]}]});new google.maps.BicyclingLayer().setMap(map);mapReady=true;updateButton();status('Search for an address or a place to get started.');};
(async()=>{try{const config=await api('/api/google/config');if(!config.browserKey)throw new Error('A Google Maps browser key is needed to load this map.');const script=document.createElement('script');script.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key:config.browserKey,callback:'initSidepath',loading:'async',v:'weekly'});script.async=true;script.onerror=()=>mapError('Google Maps could not load. Check your internet connection.');document.head.append(script);}catch(error){mapError(error.message);}})();
